loomnetwork/go-loom

- client/evm_contract.go
New EvmContract for deploying and calling methods on a EVM contract.
> Add Evm Contracts.

- cli/cli.go
- client/contract.go
- client/dapp_chain_rpc_client.go
- client/evm_contract.go
Add caller parameter to static Calls in DAppChainRPCClient, contract and evmContract.
> Support new caller paramter to Query.

- client/dapp_chain_rpc_client.go
- client/evm_contract.go
Add new txReceipt return value to EVMConteract.DeployContract
> Add GetCode to query interface.

- client/dapp_chain_rpc_client.go
To go with https://github.com/loomnetwork/loomchain/pull/148
> Change parameter to string

- .travis.yml
- Makefile
- client/plasma_cash/encoding_test.go
- client/plasma_cash/interface.go
- examples/plugins/evmproxy/cli/evmproxy.go
> Plasma tests

- plugin/mock_context.go
Need this to test contracts that call other contracts.
> Implement FakeContext.Resolve()

- builtin/types/plasma_cash/plasma_cash.proto
Change response type from bytes to plasmatx
> Update type for getting a plasma tx

- prefix.go
Needed for https://github.com/loomnetwork/loomchain/pull/364
> Move prefix declartions to go-loom

- types/types.proto
Protobuf stuff is not internal anymore
> Adjusted C# namespace

- client/dapp_chain_rpc_client.go
Reverts loomnetwork/go-loom#155
> Revert "Allow returning result on error. Allows for Tx hash on failed EVM txs."

- client/plasma_cash/eth/ethcontract/root_chain.go
- client/plasma_cash/interface.go
Updates ABI functionalities to match https://github.com/loomnetwork/plasma-cash/pull/161
> Update Plasma Cash ABI

- cli/cli_signer.go
- crypto/yubihsm.go
The `algo` parameter is unused
> Remove unused algo parameter from loadYubi

- client/dposv2/dappchain_dpos_contract.go
- client/timelock/loomtimelock_factory.go
Reverts loomnetwork/go-loom#233
> Revert "Add missing UnregisterCandidate function and new event parameter"

- client/dposv2/dappchain_dpos_contract.go
- client/timelock/loomtimelock_factory.go
Reverts loomnetwork/go-loom#234
> Revert "Revert "Add missing UnregisterCandidate function and new event parameter""

- builtin/commands/dposV2_commands.go
> adding locktime tier param to register command

- client/gateway/dappchain_gateway.go
AddAuthorizedContractMapping support in go-loom
> Add DAppChainGateway.AddAuthorizedContractMapping

- builtin/types/transfer_gateway/transfer_gateway.pb.go
- builtin/types/transfer_gateway/transfer_gateway.proto
change error_message type from bytes to string
> change err_msg type

- Makefile
Fix error when running `make` and `make deps-evm`
Changes:
- add SSHA3_DIR
- add GETH_DIR
> Fix Makefile always returns up-to-date

- builtin/commands/dposV3_commands.go
- builtin/commands/dpos_commands.go
- cli/cli.go
- cli/util.go
Refactoring for commands migration to loomchain
> Refactoring for commands migration to loomchain

- cli/cli.go
Move CallContractWithFlags & StaticCallContractWithFlags to go-loom/cli/cli.go
> Move AddContractStaticCallFlags,AddContractCallFlags to go-loom/cli

- util/util.go
Add HasPrefix util for checking if a key has a prefix
> add HasPrefix util 

- cli/cli.go
- cli/util.go
Move Parse Address and Other utility functions to go-loom
> Move Parse Address and Other utility functions to go-loom

- client/dposv3/dappchain_dpos_contract.go
Adds new methods for improved reward claiming
> Dposv3 client update

- client/gateway/dappchain_gateway.go
Add function for BEP2 token withdrawal
> Add withdrawBEP2 function

- client/rpc_client.go
ref: https://github.com/loomnetwork/go-loom/issues/348
> Handle error on HTTPDialer when giving non-prefixed URI

- plugin/contractpb/servicemap.go
ref: https://github.com/loomnetwork/go-loom/issues/144
> Make ErrMethodNotFound mention method name

- plugin/contract.go
- plugin/contractpb/contractpb.go
- plugin/mock_context.go
- plugin/plugin.go
Expose GetEnabledFeatures in Contract Context
> Show features enabled via migration in list features

- client/dapp_chain_rpc_client.go
Needed for https://github.com/loomnetwork/loomchain/pull/1350
> Set value field in client transaction

- auth/tron-signer.go
- client/gateway/dappchain_gateway.go
- common/evmcompat/helpers.go
- Fix Tron signer to produce the same message as tronweb library.
> Fix tron signer

- Makefile
This PR changes revision of yubihsm-go to include the new fix to session problem.
> Bump up yubihsm-go version

- util/util.go
Make this function available to other packages in loomchain and clusterkit
> Add PrefixRangeEnd to util

- builtin/types/dposv3/dposv3.pb.go
- builtin/types/dposv3/dposv3.proto
ref : https://github.com/loomnetwork/loomchain/issues/1611
> Add UnbondAllRequest message type to DPOS3 

- .github/pr.yml
travis-ci.org is no more and I can't be bothered migrating to .com
> Add a Github action to build PRs
